version: '2'
services:
  api:
    extends:
      file: docker-compose-common.yml
      service: api
    command: yarn start:dev
    ports:
      - "127.0.0.1:81:8080"
    environment:
      PORT: 8080

  frontend:
    build:
      context: ./frontend
      args:
        ENV_FILE: local
    command: yarn start
    ports:
      - "127.0.0.1:80:8080"
    volumes:
      - "./frontend/.env.local:/app/.env"
      - "./frontend/src:/app/src"
      - "./frontend/server:/app/server"
      - "./frontend/package.json:/app/package.json"
    environment:
      PORT: 8080